# Generated by Django 4.2.1 on 2023-05-17 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_transction_transction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transction',
            name='transction_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer'), ('Receive', 'Receive')], max_length=20),
        ),
    ]
