# Generated by Django 4.2.1 on 2023-05-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0003_alter_transction_transction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transction',
            name='amount_type',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=20, null=True),
        ),
    ]
