# Generated by Django 4.2.1 on 2023-05-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_transction_amount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transction',
            name='amount_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=20, null=True),
        ),
    ]
