# Generated by Django 4.2.1 on 2023-05-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_transction_amount_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transction',
            name='balance_after_transaction',
        ),
    ]
